# SPDX-License-Identifier: Apache-2.0
[package]
name = "segme"
version = "0.1.0"
edition = "2018"

[dependencies]
unicode-segmentation = "1.9.0"
unicode_names2 = "0.5.0"
wasm-bindgen = "0.2.78"

[lib]
crate-type = ["cdylib", "rlib"]
